#!/bin/bash
#SBATCH --cpus-per-task=8       #Quantidade de núcleos
#SBATCH --job-name=yolov8x
#SBATCH --time=1-00:00          #Tempo máximo do job no formato DIAS-HORAS:MINUTOS
#SBATCH --hint=compute_bound
#SBATCH --mail-user=jefferson@ppgsc.ufrn.br
#SBATCH --mail-type=ALL
#SBATCH --mem=50000
#SBATCH --partition=gpu-8-v100
#SBATCH --gpus-per-node=2   # Número GPUs por nó
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

module load softwares/python/3.10.5-gnu8

pip3 install ultralytics --quiet
pip3 install roboflow --quiet

python3.10 yolo.py
